### ISSUE TITLE
Issues with common named service handlers

### ISSUE THREAD

**Issue by dapriett** [goldwasserexchange/serverless-plugin-webpack#12]
I noticed an issue when services handlers are named similarly like so:

```
  serviceA:
     handler: api/serviceA/handler.handler
  serviceB:
     handler: api/serviceB/handler.handler
```

This plugin strips the handlers down to the base paths, and they basically end up clobbering each other.  Recommend instead compiling to sub-directories by service name (.webpack/serviceA/handler.js)
