### ISSUE TITLE
Individual package.include have the wrong base folder

### ISSUE THREAD

**Issue by geovanisouza92** [goldwasserexchange/serverless-plugin-webpack#21]
Hi, thank you for this plugin, it helps a lot!

I found a problem while packaging functions: If I set the package.include of that function, usually we use some path from the root of the service (where `serverless.yml` lives), but while manipulating the configuration, [this](https://github.com/goldwasserexchange/serverless-plugin-webpack/blob/master/src/index.js#L44) line changes the service path, that is used later for packaging.

Long story short:

If I type this on `serverless.yml`:

```yaml

functions:
  hello:
    handler: aws/hello.handler
    events:
      - http:
          method: any
          path: /hello
    package:
      include:
        - .gitignore # this file is on the project root
```

the final zip does not include it, but if I change to:

```yaml
    package:
      include:
        - ../.gitignore # relative path from .webpack
```

It works as expected.
