### ISSUE TITLE
How to include directory with files on root of service

### ISSUE THREAD

**Issue by dbeja** [goldwasserexchange/serverless-plugin-webpack#50]
I have a directory on root of my service that wasn't being included on the zip file so I added copy-webpack-plugin to webpack.config.js:
```
plugins: [
	 new CopyWebpackPlugin([{
		 from: path.join(__dirname, "templates")
	 }])
 ]
```

Now I have all the files that are inside templates directory on the root of the service, and I can also see them on Lambda console so I can get them on lambda code.

The problem is that when I change to put the files inside a directory:

```
plugins: [
	 new CopyWebpackPlugin([{
		 from: path.join(__dirname, "templates"), to: "templates"
	 }])
 ]
```

The directory shows up on the zip but the folder doesn't show up on Lambda console and so the files are not available inside lambda code.

I even tried to add the package configuration on serverless.yml:

```
package:
  include:
    - templates/**
```
but still no directory or files.

I'm also not 100% sure if this is related with serverless-plugin-webpack or not but it seems to be the only difference I have in my project.

**Comment by jogold** [comment]
Hi @dbeja,

Can you try to set the `package` configuration at the function level to see if it works?
```
function:
  hello:
    package:
      include:
        - templates/**
```

**Comment by jogold** [comment]
Also can you share your `node` and `serverless` version? It should work with the `package` configuration in `serverless.yml`, you shouldn't need `CopyWebpackPlugin` for this.

**Comment by dbeja** [comment]
Tried at function level but still not works.

Serverless: 1.26.0
Node: v6.7.0

Also tried to not use CopyWebpackPlugin.

**Comment by dbeja** [comment]
I have this on my webpack.config.js:

```
module.exports = {
	target: "node",
	externals: [
		/aws-sdk/,
	],
	module: {
		rules: [{
			test: /\.js$/,
			loader: "babel-loader",
			exclude: /node_modules/
		}]
	}
};

```

And on serverless.yml I have this:

```
plugins:
  - serverless-plugin-webpack

functions:
  sendEmail:
    handler: functions/sendEmail.main
    package:
      include:
        - templates/**

```

I'm also using serverless-plugin-webpack 1.3.0.

The templates folder show up on the zip file of the function if I just do sls package, but it's not include on the lambda.
