### ISSUE TITLE
module initialization error with jsonpath library

### ISSUE THREAD

**Issue by jefftham** [goldwasserexchange/serverless-plugin-webpack#61]
I am able to deploy my code to aws, and it is working fine with or without serverless-plugin-webpack.
However, when i includes "jsonpath" in the lambda code, and deploy it with serverless-plugin-webpack it throws me 'module initialization error'.

```
// handler.js
'use strict';

const jp = require("jsonpath");

module.exports.hello = (event, context, callback) => {
  const response = {
    statusCode: 200,
    body: JSON.stringify({
      message: 'Go Serverless v1.0! Your function executed successfully!',
      input: event,
    }),
  };

  callback(null, response);
};

```
```
// webpack.config.js

module.exports = {
  // entry: set by the plugin
  // output: set by the plugin
  target   : 'node',
  devtool: 'source-map',
  externals: [
    /aws-sdk/, // Available on AWS Lambda
  ],
  module   : {
    rules: [
      {
        test   : /\.js$/,
        loader : 'babel-loader',
        query  : {
          presets: [
            [
              'env', {
                target     : {node: 8.10}, // Node version on AWS Lambda
                useBuiltIns: true, // Prefer built in ES features as much as possible instead of using polyfills
                modules    : false, // See https://babeljs.io/docs/plugins/preset-env/#optionsmodules
                loose      : true,
              },
            ],
            'env',
            'stage-0',
          ],
        },
      },
    ],
  },
};
```
```

service: slsTest

provider:
  name: aws
  runtime: nodejs8.10


package:
  individually: true

plugins:
  - serverless-plugin-webpack

functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: rate(1 minute)
          enable: true   


```

```
// cloudwatch log

START RequestId: bd2fa50f-65a7-11e8-a82e-d1b988abfeca Version: $LATEST
module initialization error: Error
at tryStatSync (fs.js:517:13)
at Object.fs.readFileSync (fs.js:553:3)
at Object.<anonymous> (/var/task/handler.js:6774:30)
at __webpack_require__ (/var/task/handler.js:21:30)
at Object.module.exports.module.exports.len (/var/task/handler.js:7051:15)
at __webpack_require__ (/var/task/handler.js:21:30)
at Object.<anonymous> (/var/task/handler.js:736:14)
at __webpack_require__ (/var/task/handler.js:21:30)
at Object.module.exports.ES5Regex.NonAsciiIdentifierStart (/var/task/handler.js:574:18)
at __webpack_require__ (/var/task/handler.js:21:30)
END RequestId: bd2fa50f-65a7-11e8-a82e-d1b988abfeca
```
